"""Repository 端口。

当前唯一实现为 InMemory（无需数据库即可联调与测试）；
接入 PostgreSQL 时新增 SQL 实现，服务层与 API 不变。
"""

from typing import Protocol
from uuid import UUID

from hydrolab.domain.entities import (
    AuditLog,
    Invitation,
    ResourceGrant,
    Session,
    ShareLink,
    User,
)
from hydrolab.domain.enums import ResourceType


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def update(self, user: User) -> User: ...
    async def count(self) -> int: ...


class InvitationRepository(Protocol):
    async def add(self, invitation: Invitation) -> Invitation: ...
    async def get(self, invitation_id: UUID) -> Invitation | None: ...
    async def get_by_token_hash(self, token_hash: str) -> Invitation | None: ...
    async def update(self, invitation: Invitation) -> Invitation: ...
    async def list_pending(self) -> list[Invitation]: ...


class SessionRepository(Protocol):
    async def add(self, session: Session) -> Session: ...
    async def get_by_token_hash(self, token_hash: str) -> Session | None: ...
    async def get_by_refresh_hash(self, refresh_hash: str) -> Session | None: ...
    async def update(self, session: Session) -> Session: ...


class GrantRepository(Protocol):
    async def add(self, grant: ResourceGrant) -> ResourceGrant: ...
    async def delete(self, grant_id: UUID) -> bool: ...
    async def get(
        self, resource_type: ResourceType, resource_id: UUID, subject_id: UUID
    ) -> ResourceGrant | None: ...
    async def get_by_id(self, grant_id: UUID) -> ResourceGrant | None: ...
    async def list_for_resource(
        self, resource_type: ResourceType, resource_id: UUID
    ) -> list[ResourceGrant]: ...


class ShareLinkRepository(Protocol):
    async def add(self, link: ShareLink) -> ShareLink: ...
    async def get(self, link_id: UUID) -> ShareLink | None: ...
    async def get_by_token_hash(self, token_hash: str) -> ShareLink | None: ...
    async def update(self, link: ShareLink) -> ShareLink: ...
    async def list_by_creator(self, user_id: UUID) -> list[ShareLink]: ...


class AuditLogRepository(Protocol):
    async def add(self, entry: AuditLog) -> AuditLog: ...
    async def list_recent(self, limit: int = 100) -> list[AuditLog]: ...
