"""initial schema: all hydrolab domain tables

Revision ID: 4e409406eb80
Revises: 0001_baseline
Create Date: 2026-09-13 00:53:54.302635
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import hydrolab.db.base

revision: str = '4e409406eb80'
down_revision: str | Sequence[str] | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_owner_id'), 'artifacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_artifacts_resource_id'), 'artifacts', ['resource_id'], unique=False)
    op.create_table('asset_folders',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('parent_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('path_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_folders_owner_id'), 'asset_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_asset_folders_path_key'), 'asset_folders', ['path_key'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('actor_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('source_run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('source_experiment_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('artifact_key', sa.String(length=500), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=100), nullable=False),
    sa.Column('model_signature', sa.String(length=200), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=True),
    sa.Column('target_names', sa.JSON(), nullable=True),
    sa.Column('scaler_signature', sa.String(length=200), nullable=True),
    sa.Column('optimizer_included', sa.Boolean(), nullable=False),
    sa.Column('scheduler_included', sa.Boolean(), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_owner_id'), 'checkpoints', ['owner_id'], unique=False)
    op.create_index(
        op.f('ix_checkpoints_source_experiment_version_id'),
        'checkpoints',
        ['source_experiment_version_id'],
        unique=False
    )
    op.create_index(op.f('ix_checkpoints_source_run_id'), 'checkpoints', ['source_run_id'], unique=False)
    op.create_table('code_repositories',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_repositories_owner_id'), 'code_repositories', ['owner_id'], unique=False)
    op.create_table('code_versions',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('repository_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=True),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=100), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('frozen_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_versions_repository_id'), 'code_versions', ['repository_id'], unique=False)
    op.create_table('dataset_import_jobs',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('dataset_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('artifact_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('detected_format', sa.String(length=30), nullable=False),
    sa.Column('bundle_entries', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('retry_of_job_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_import_jobs_dataset_id'), 'dataset_import_jobs', ['dataset_id'], unique=False)
    op.create_index(
        op.f('ix_dataset_import_jobs_idempotency_key'), 'dataset_import_jobs', ['idempotency_key'], unique=False
    )
    op.create_index(op.f('ix_dataset_import_jobs_owner_id'), 'dataset_import_jobs', ['owner_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('dataset_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('object_prefix', sa.String(length=500), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=100), nullable=True),
    sa.Column('parent_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('frozen_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('folder_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_table('environment_versions',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('environment_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_image', sa.String(length=500), nullable=False),
    sa.Column('python_version', sa.String(length=20), nullable=False),
    sa.Column('dependency_file', sa.String(length=500), nullable=True),
    sa.Column('dependency_content', sa.String(length=10000), nullable=True),
    sa.Column('image_digest', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=100), nullable=False),
    sa.Column('frozen_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_environment_versions_environment_id'), 'environment_versions', ['environment_id'], unique=False
    )
    op.create_table('experiment_drafts',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('dataset_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('code_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('template_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('environment_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('parameter_values', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_drafts_owner_id'), 'experiment_drafts', ['owner_id'], unique=False)
    op.create_table('experiment_templates',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('code_repository_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_templates_owner_id'), 'experiment_templates', ['owner_id'], unique=False)
    op.create_table('experiment_versions',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('experiment_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('resolved_config', sa.JSON(), nullable=True),
    sa.Column('config_hash', sa.String(length=100), nullable=False),
    sa.Column('frozen_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_versions_config_hash'), 'experiment_versions', ['config_hash'], unique=False)
    op.create_index(
        op.f('ix_experiment_versions_experiment_id'), 'experiment_versions', ['experiment_id'], unique=False
    )
    op.create_table('experiments',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_owner_id'), 'experiments', ['owner_id'], unique=False)
    op.create_table('export_manifests',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('result_ids', sa.JSON(), nullable=True),
    sa.Column('artifact_ids', sa.JSON(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_manifests_owner_id'), 'export_manifests', ['owner_id'], unique=False)
    op.create_table('field_mappings',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('import_job_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('confirmed_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mappings_import_job_id'), 'field_mappings', ['import_job_id'], unique=False)
    op.create_table('gpu_leases',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=False),
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('expires_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('heartbeat_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gpu_index')
    )
    op.create_index(op.f('ix_gpu_leases_run_id'), 'gpu_leases', ['run_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('inviter_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('expires_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('accepted_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_inviter_id'), 'invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('metric_points',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('result_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('split', sa.String(length=20), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=True),
    sa.Column('basin_id', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_points_result_id'), 'metric_points', ['result_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('published_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('parameter_presets',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('template_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_presets_owner_id'), 'parameter_presets', ['owner_id'], unique=False)
    op.create_index(
        op.f('ix_parameter_presets_template_version_id'), 'parameter_presets', ['template_version_id'], unique=False
    )
    op.create_table('plot_specs',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('result_ids', sa.JSON(), nullable=True),
    sa.Column('plot_type', sa.String(length=80), nullable=False),
    sa.Column('data_selection', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('script_ref', sa.String(length=200), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_specs_owner_id'), 'plot_specs', ['owner_id'], unique=False)
    op.create_table('resource_grants',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('granted_by', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('expires_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_grants_resource_id'), 'resource_grants', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_grants_subject_id'), 'resource_grants', ['subject_id'], unique=False)
    op.create_table('resource_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('gpu_index', sa.Integer(), nullable=False),
    sa.Column('utilization_percent', sa.Float(), nullable=False),
    sa.Column('memory_used_mb', sa.Integer(), nullable=False),
    sa.Column('memory_total_mb', sa.Integer(), nullable=False),
    sa.Column('sampled_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_samples_run_id'), 'resource_samples', ['run_id'], unique=False)
    op.create_table('result_artifacts',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('result_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_artifacts_result_id'), 'result_artifacts', ['result_id'], unique=False)
    op.create_table('results',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('dataset_version_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_dataset_version_id'), 'results', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_results_owner_id'), 'results', ['owner_id'], unique=False)
    op.create_index(op.f('ix_results_run_id'), 'results', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('occurred_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_event_type'), 'run_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('run_executions',
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('gpu_indices', sa.JSON(), nullable=True),
    sa.Column('started_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('stream', sa.String(length=20), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_logs_run_id'), 'run_logs', ['run_id'], unique=False)
    op.create_table('run_stages',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('run_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_stages_run_id'), 'run_stages', ['run_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('experiment_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('experiment_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_experiment_id'), 'runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_runs_experiment_version_id'), 'runs', ['experiment_version_id'], unique=False)
    op.create_index(op.f('ix_runs_idempotency_key'), 'runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_runs_owner_id'), 'runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('runtime_environments',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('owner_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('updated_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_environments_owner_id'), 'runtime_environments', ['owner_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('user_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=200), nullable=False),
    sa.Column('expires_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('refresh_expires_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('resource_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('allowed_artifact_kinds', sa.JSON(), nullable=True),
    sa.Column('created_by', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('expires_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_created_by'), 'share_links', ['created_by'], unique=False)
    op.create_index(op.f('ix_share_links_resource_id'), 'share_links', ['resource_id'], unique=False)
    op.create_index(op.f('ix_share_links_token_hash'), 'share_links', ['token_hash'], unique=True)
    op.create_table('template_versions',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('template_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('code_version_id', hydrolab.db.base.UUID36(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('argv', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('input_contract', sa.JSON(), nullable=True),
    sa.Column('output_contract', sa.JSON(), nullable=True),
    sa.Column('frozen_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('id', hydrolab.db.base.UUID36(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', hydrolab.db.base.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_share_links_token_hash'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_resource_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_created_by'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_runtime_environments_owner_id'), table_name='runtime_environments')
    op.drop_table('runtime_environments')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_owner_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_idempotency_key'), table_name='runs')
    op.drop_index(op.f('ix_runs_experiment_version_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_experiment_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_run_stages_run_id'), table_name='run_stages')
    op.drop_table('run_stages')
    op.drop_index(op.f('ix_run_logs_run_id'), table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_table('run_executions')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_event_type'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_results_run_id'), table_name='results')
    op.drop_index(op.f('ix_results_owner_id'), table_name='results')
    op.drop_index(op.f('ix_results_dataset_version_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_result_artifacts_result_id'), table_name='result_artifacts')
    op.drop_table('result_artifacts')
    op.drop_index(op.f('ix_resource_samples_run_id'), table_name='resource_samples')
    op.drop_table('resource_samples')
    op.drop_index(op.f('ix_resource_grants_subject_id'), table_name='resource_grants')
    op.drop_index(op.f('ix_resource_grants_resource_id'), table_name='resource_grants')
    op.drop_table('resource_grants')
    op.drop_index(op.f('ix_plot_specs_owner_id'), table_name='plot_specs')
    op.drop_table('plot_specs')
    op.drop_index(op.f('ix_parameter_presets_template_version_id'), table_name='parameter_presets')
    op.drop_index(op.f('ix_parameter_presets_owner_id'), table_name='parameter_presets')
    op.drop_table('parameter_presets')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_metric_points_result_id'), table_name='metric_points')
    op.drop_table('metric_points')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_inviter_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_gpu_leases_run_id'), table_name='gpu_leases')
    op.drop_table('gpu_leases')
    op.drop_index(op.f('ix_field_mappings_import_job_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    op.drop_index(op.f('ix_export_manifests_owner_id'), table_name='export_manifests')
    op.drop_table('export_manifests')
    op.drop_index(op.f('ix_experiments_owner_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_experiment_versions_experiment_id'), table_name='experiment_versions')
    op.drop_index(op.f('ix_experiment_versions_config_hash'), table_name='experiment_versions')
    op.drop_table('experiment_versions')
    op.drop_index(op.f('ix_experiment_templates_owner_id'), table_name='experiment_templates')
    op.drop_table('experiment_templates')
    op.drop_index(op.f('ix_experiment_drafts_owner_id'), table_name='experiment_drafts')
    op.drop_table('experiment_drafts')
    op.drop_index(op.f('ix_environment_versions_environment_id'), table_name='environment_versions')
    op.drop_table('environment_versions')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_dataset_import_jobs_owner_id'), table_name='dataset_import_jobs')
    op.drop_index(op.f('ix_dataset_import_jobs_idempotency_key'), table_name='dataset_import_jobs')
    op.drop_index(op.f('ix_dataset_import_jobs_dataset_id'), table_name='dataset_import_jobs')
    op.drop_table('dataset_import_jobs')
    op.drop_index(op.f('ix_code_versions_repository_id'), table_name='code_versions')
    op.drop_table('code_versions')
    op.drop_index(op.f('ix_code_repositories_owner_id'), table_name='code_repositories')
    op.drop_table('code_repositories')
    op.drop_index(op.f('ix_checkpoints_source_run_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_source_experiment_version_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_owner_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_asset_folders_path_key'), table_name='asset_folders')
    op.drop_index(op.f('ix_asset_folders_owner_id'), table_name='asset_folders')
    op.drop_table('asset_folders')
    op.drop_index(op.f('ix_artifacts_resource_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
