"""B3 代码、模板与环境仓储端口。"""

from typing import Protocol
from uuid import UUID

from hydrolab.code_assets.entities import (
    CodeRepository,
    CodeVersion,
    EnvironmentVersion,
    ExperimentTemplate,
    ParameterPreset,
    RuntimeEnvironment,
    TemplateVersion,
)


class CodeRepositoryStore(Protocol):
    async def add(self, item: CodeRepository) -> CodeRepository: ...
    async def get(self, item_id: UUID) -> CodeRepository | None: ...
    async def list_by_owner(self, owner_id: UUID) -> list[CodeRepository]: ...


class CodeVersionStore(Protocol):
    async def add(self, item: CodeVersion) -> CodeVersion: ...
    async def get(self, item_id: UUID) -> CodeVersion | None: ...
    async def list_by_repository(self, repository_id: UUID) -> list[CodeVersion]: ...
    async def next_version_no(self, repository_id: UUID) -> int: ...


class TemplateStore(Protocol):
    async def add(self, item: ExperimentTemplate) -> ExperimentTemplate: ...
    async def get(self, item_id: UUID) -> ExperimentTemplate | None: ...
    async def list_by_owner(self, owner_id: UUID) -> list[ExperimentTemplate]: ...


class TemplateVersionStore(Protocol):
    async def add(self, item: TemplateVersion) -> TemplateVersion: ...
    async def get(self, item_id: UUID) -> TemplateVersion | None: ...
    async def list_by_template(self, template_id: UUID) -> list[TemplateVersion]: ...
    async def next_version_no(self, template_id: UUID) -> int: ...


class EnvironmentStore(Protocol):
    async def add(self, item: RuntimeEnvironment) -> RuntimeEnvironment: ...
    async def get(self, item_id: UUID) -> RuntimeEnvironment | None: ...
    async def list_by_owner(self, owner_id: UUID) -> list[RuntimeEnvironment]: ...


class EnvironmentVersionStore(Protocol):
    async def add(self, item: EnvironmentVersion) -> EnvironmentVersion: ...
    async def get(self, item_id: UUID) -> EnvironmentVersion | None: ...
    async def list_by_environment(self, environment_id: UUID) -> list[EnvironmentVersion]: ...
    async def next_version_no(self, environment_id: UUID) -> int: ...


class PresetStore(Protocol):
    async def add(self, item: ParameterPreset) -> ParameterPreset: ...
    async def get(self, item_id: UUID) -> ParameterPreset | None: ...
    async def list_by_template_version(self, template_version_id: UUID) -> list[ParameterPreset]: ...
